name: EAS Build

on:
  push:
    paths:
      - ".github/workflows/easbuild.yml"
    # branches:
    # - main

jobs:
  build:
    name: Install and build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v7
        with:
          expo-version: 5.x
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: yarn install

      - name: Build on EAS
        run: eas build --platform android --profile staging --non-interactive > apkOutput.txt

      - name: Output of apk file path
        run: |
          cat apkOutput.txt
      #     echo "APK_LOCATION=$(echo cat apkOutput.txt | sed -n 's/^.*Build details \(.*\)$/\1/gp')"
      # - run: echo ${{ env.APK_LOCATION }}

      - name: Get apk path
        id: vars
        run: echo ::set-output name=filepath::$(cat cat apkOutput.txt | sed -n 's/^.*Build details \(.*\)$/\1/gp')
      - name: Test output
        run: echo ${{ steps.vars.outputs.filepath }}

      # - name: Upload apk path
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: apkoutput
      #     path: apkOutput.txt
