name: EAS Build

on:
  push:
    paths:
      - ".github/workflows/easbuild.yml"
    # branches:
    # - main

jobs:
  build:
    name: Install and build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v7
        with:
          expo-version: 5.x
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Cache yarn dependencies
        id: cache-dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('package.json', 'yarn.lock') }}

      - name: Install dependencies
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: yarn install

      - name: Build on EAS
        run: eas build --platform android --profile staging --non-interactive > apkOutput.txt

      - name: Output of apkOutput
        run: cat apkOutput.txt

      - name: Get apk path
        run: |
          echo $(cat apkOutput.txt | sed -n "s/^.*Build details: \(.*\)$/\1/gp")

      - name: Save APK path in variable
        id: vars
        run: |
          echo "::set-output name=APK_PATH::$(cat apkOutput.txt | sed -n '/Android app:/{n;p;}')"

      - name: Print apk path
        run: echo ${{ steps.vars.outputs.APK_PATH }}

      # - name: Upload apk path
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: apkoutput
      #     path: apkOutput.txt
